# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frlr1 <- function(X, Y, COV) {
    .Call(`_fRLR_frlr1`, X, Y, COV)
}

frlr2 <- function(R_X, R_idx1, R_idx2, R_Y, R_COV) {
    .Call(`_fRLR_frlr2`, R_X, R_idx1, R_idx2, R_Y, R_COV)
}

rcpp_hello_world <- function() {
    .Call(`_fRLR_rcpp_hello_world`)
}

